### ISSUE TITLE
Add support for formatting the protobuf source files according to the google style guide

### ISSUE THREAD

**Issue by profhenry** [GEBIT/protobuf-dt#2]
Formatting the protobuf sources files currently does not respect the [GoogleStyleGuide](https://protobuf.dev/programming-guides/style/). It would be nice if it does.

In addition some configuration possibilities would also be nice, for example the line length in case you want to deviate from the style guide.

**Comment by S1artie** [comment]
The autoformatter was adjusted to more closely comply with the Google Style Guide in the following aspects:

- It now has its own "tabs to spaces" setting which can differ from the common Eclipse-wide editor setting (and which defaults to true), using two spaces to replace a tab
- It also has its own max line length setting, which as well can differ from the common Eclipse-wide editor setting (and which defaults to 120, so if someone really, really wants to comply with Google Style Guide 100% you'll have to set this to 80, but...come on, only 80 characters on modern screens?)
- It was ensured that the tab-to-spaces option applies not just to the formatter, but also to the editor itself (dynamically replacing tabs with spaces if it's enabled) so edits to .proto files should now be conformant if tabs-to-spaces is enabled for the proto editor

The new .proto-editor-specific settings are available in Eclipse preferences where there was already a separate settings pane for the proto editor.
