### ISSUE TITLE
Add index and name validation for enums

### ISSUE THREAD

**Issue by profhenry** [GEBIT/protobuf-dt#4]
For messages indices are validated, you get the following validation error.

![image](https://github.com/user-attachments/assets/d23fb633-3a78-4aec-9bfe-bed571ffc4d2)

Duplicate field names in messages are not detected, the following does not produce any error.
```proto
message MyMessage {
  string my_string = 1;
  int64 my_string = 2;
}
```

For enums neither enum values nor indices are validated, the following does not produce any error.
```proto
enum MyEnum {
  MY_VALUE_1 = 0;
  MY_VALUE_2 = 0;
  MY_VALUE_1 = 3;
}
```

Validation also needs to account reserved fields, for messages this works fine, you get the following error.

![image](https://github.com/user-attachments/assets/4bdc98c6-76a6-4d4d-a5a0-56d8d62de52e)

Reserved enum values and indices should be taken into account.
Please note that this also has to work for enums embedded in messages!

**Comment by S1artie** [comment]
Resolved in version 2.5.2
