### ISSUE TITLE
Incorrect formating

### ISSUE THREAD

**Issue by marcel-bien-gebit** [GEBIT/protobuf-dt#5]
If there is a comment in the first line after another nesting, this is not indented correctly.

Example 1:

![grafik](https://github.com/user-attachments/assets/00162e6c-ef11-4ac4-83d7-610b3b84cad8)

after auto format:

![grafik](https://github.com/user-attachments/assets/8d350811-f13d-4a35-b3a0-a05f8e45af7e)

Example 2:

![grafik](https://github.com/user-attachments/assets/5782e268-e186-4d87-98fc-599245443cd8)

after auto format:

![grafik](https://github.com/user-attachments/assets/c12e907e-a268-4b1f-ad6d-b8afd3b22043)

**Comment by S1artie** [comment]
There is a related case of incorrect formatting, also connected to the oneof keyword: an attribute after the oneof bracket closure is pulled into the same line as the closing bracket right now:
![SCR-20240823-jslc](https://github.com/user-attachments/assets/e53a10d0-0e87-4c8b-b8c4-a31989084f38)
